# Header
menu:
  Root: /
#  Архив: /archives
rss: /atom.xml

# Content
excerpt_link: Читать дальше →
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
#- tag
- tagcloud
#- archive
#- recent_posts

# Miscellaneous
google_analytics: 'UA-57420841-1'
favicon: /favicon.png
twitter: yurtaev
google_plus: 'https://www.google.com/+EgorYurtaev'
fb_admins:
fb_app_id:
